# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "PupEyes: Your Buddy for Pupil Size and Eye Movement Data Analysis"
author: Han Zhang (hanzh@umich.edu)
logo: ../banner.jpg
copyright: "2025"

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "*.ipynb_checkpoints", "*skip.ipynb"]
# Auto-exclude files not in the toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add Sphinx extensions
sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  config:
    add_module_names: true
    suppress_warnings: ["mystnb.unknown_mime_type"]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/HanZhang-psych/pupeyes
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ../favicon.jpg
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  home_page_in_navbar: true
  analytics:
    google_analytics_id       : ""  # A GA id that can be used to track book views.