#!/bin/bash

# # Copy data files to the binder environment
# mkdir -p docs/data
# cp -r docs/data/* docs/data/ 2>/dev/null || true

# install additional packages
pip install I2MC
pip install pupeyes
pip install mne
pip install joblib

# build jupyterlab
jupyter lab build --minimize=False